#version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home                      # 1
      - ./jenkins.yaml:/var/jenkins_home/jenkins.yaml       # 2
    networks:
      - jenkins-network

  jenkins-agent:
    image: jenkins/inbound-agent
    container_name: jenkins-agent
    environment:
      - JENKINS_IMAGE="jenkins/jenkins:lts"
      - CONTAINER_NAME="jenkins-server"
      - JENKINS_PORT="8080"
      - JENKINS_AGENT_PORT="50000"
      - VOLUME_NAME="jenkins_home"
      - CONFIG_DIR="$(pwd)/jenkins_configuration"
      - JENKINS_ADMIN_PASSWORD=wsxcde32!QAZ
      - JENKINS_URL=http://jenkins-server:8080
      - JENKINS_AGENT_NAME=agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_SECRET=d7e0ebd3d8d6106d2da3c200d38baa5e56fe99e98cfc41e1e7e5dc96471415c5  # Укажите секрет здесь
    volumes:
      - agent_workdir:/home/jenkins/agent
    depends_on:
      - jenkins
    networks:
      - jenkins-network

volumes:
  jenkins_home:
  agent_workdir:

networks:
  jenkins-network:
